### PR TITLE
Overloaded Classes

### PR DESCRIPTION
**Pull request by AndreiLupuleasa**
implemented interfaces removed in child class in request

### CODE REVIEW

**Comment by AndreiLupuleasa** [comment]
@dcarbone I've accidentally made a pull request on qpleple/cloudstack-php-client but I've closed it.
I searched on google and unfortunately I can't erase it permanently due to github terms.

https://stackoverflow.com/questions/18318097/delete-a-closed-pull-request-from-github

I hope I won't create you any problems. I'm sorry.

**Comment by dcarbone** [comment]
I can just close it.

**Comment by AndreiLupuleasa** [comment]
Not this one. I've closed the one on qpleople. This one is on myEna

image

**Comment by dcarbone** [comment]
ok, i've opened it again...

**Pull request closed without merging**
